"""DomainIQ Python Library - A modern Python client for the DomainIQ API.

This library provides both synchronous and asynchronous clients for interacting
with the DomainIQ API, enabling domain intelligence gathering, WHOIS lookups,
DNS queries, and monitoring capabilities.
"""

from .async_client import AsyncDomainIQClient
from .client import DomainIQClient
from .config import Config, ConfigKwargs
from .exceptions import (
    DomainIQAPIError,
    DomainIQAuthenticationError,
    DomainIQConfigurationError,
    DomainIQError,
    DomainIQPartialResultsError,
    DomainIQRateLimitError,
    DomainIQTimeoutError,
    DomainIQValidationError,
)
from .models import (
    BulkWhoisType,
    DNSRecordType,
    DNSResult,
    DomainCategory,
    DomainReport,
    DomainSearchFilters,
    DomainSnapshot,
    EmailReportResult,
    IpReportResult,
    KeywordMatchType,
    MatchType,
    MonitorActionResult,
    MonitorItemOptions,
    MonitorItemType,
    MonitorReport,
    MonitorReportType,
    NameReportResult,
    OrganizationReportResult,
    QueueResult,
    ReverseIpSearchType,
    ReverseMatchType,
    ReverseMxSearchType,
    ReverseSearchResult,
    ReverseSearchType,
    SearchResult,
    SnapshotOptions,
    WhoisResult,
)
from .protocols import (
    AsyncBulkProtocol,
    AsyncDNSProtocol,
    AsyncDomainAnalysisProtocol,
    AsyncDomainIQClientProtocol,
    AsyncMonitorProtocol,
    AsyncQueueProtocol,
    AsyncReportProtocol,
    AsyncSearchProtocol,
    AsyncWhoisProtocol,
    BulkProtocol,
    DNSProtocol,
    DomainAnalysisProtocol,
    DomainIQClientProtocol,
    MonitorProtocol,
    QueueProtocol,
    ReportProtocol,
    SearchProtocol,
    WhoisProtocol,
)

__version__ = "3.1.0"
__author__ = "seifreed"
__email__ = "mriverolopez@gmail.com"
__license__ = "MIT"

__all__ = [
    "AsyncBulkProtocol",
    "AsyncDNSProtocol",
    "AsyncDomainAnalysisProtocol",
    "AsyncDomainIQClient",
    "AsyncDomainIQClientProtocol",
    "AsyncMonitorProtocol",
    "AsyncQueueProtocol",
    "AsyncReportProtocol",
    "AsyncSearchProtocol",
    "AsyncWhoisProtocol",
    "BulkProtocol",
    "BulkWhoisType",
    "Config",
    "ConfigKwargs",
    "DNSProtocol",
    "DNSRecordType",
    "DNSResult",
    "DomainAnalysisProtocol",
    "DomainCategory",
    "DomainIQAPIError",
    "DomainIQAuthenticationError",
    "DomainIQClient",
    "DomainIQClientProtocol",
    "DomainIQConfigurationError",
    "DomainIQError",
    "DomainIQPartialResultsError",
    "DomainIQRateLimitError",
    "DomainIQTimeoutError",
    "DomainIQValidationError",
    "DomainReport",
    "DomainSearchFilters",
    "DomainSnapshot",
    "EmailReportResult",
    "IpReportResult",
    "KeywordMatchType",
    "MatchType",
    "MonitorActionResult",
    "MonitorItemOptions",
    "MonitorItemType",
    "MonitorProtocol",
    "MonitorReport",
    "MonitorReportType",
    "NameReportResult",
    "OrganizationReportResult",
    "QueueProtocol",
    "QueueResult",
    "ReportProtocol",
    "ReverseIpSearchType",
    "ReverseMatchType",
    "ReverseMxSearchType",
    "ReverseSearchResult",
    "ReverseSearchType",
    "SearchProtocol",
    "SearchResult",
    "SnapshotOptions",
    "WhoisProtocol",
    "WhoisResult",
]
