"""Bulk operation endpoint mixins (sync and async).

_BulkMixin and _AsyncBulkMixin are intentionally near-identical.
Python requires 'await' inside 'async def'; the two classes cannot share
implementation while maintaining correct coroutine semantics, mypy strict
compliance, and IDE support. All extractable logic lives in parameter-builder
modules and deserializers.py; what remains is structural boilerplate.
"""

from __future__ import annotations

from typing import cast

from ._base_client import _AsyncRequestable, _SyncRequestable
from ._models import BulkDNSResult, BulkWhoisResult, BulkWhoisType
from ._params.bulk import (
    build_bulk_dns_params,
    build_bulk_whois_ip_params,
    build_bulk_whois_params,
)
from .utils import csv_to_dict_list


class _BulkMixin(_SyncRequestable):
    def bulk_dns(self, domains: list[str]) -> list[BulkDNSResult]:
        """Perform bulk DNS lookups."""
        csv_response = self._make_csv_request(build_bulk_dns_params(domains))
        return cast(
            "list[BulkDNSResult]",
            csv_to_dict_list(csv_response) if csv_response else [],
        )

    def bulk_whois(
        self, items: list[str], lookup_type: BulkWhoisType = BulkWhoisType.LIVE
    ) -> list[BulkWhoisResult]:
        """Perform bulk WHOIS lookups."""
        csv_response = self._make_csv_request(
            build_bulk_whois_params(items, lookup_type)
        )
        return cast(
            "list[BulkWhoisResult]",
            csv_to_dict_list(csv_response) if csv_response else [],
        )

    def bulk_whois_ip(self, domains: list[str]) -> list[BulkWhoisResult]:
        """Perform bulk domain IP WHOIS lookups."""
        csv_response = self._make_csv_request(build_bulk_whois_ip_params(domains))
        return cast(
            "list[BulkWhoisResult]",
            csv_to_dict_list(csv_response) if csv_response else [],
        )


# --- BEGIN GENERATED ---
# Async counterpart of the sync class above — generated by scripts/generate_mixins.py
# Edit the sync class, then run `make gen-mixins` to regenerate.
class _AsyncBulkMixin(_AsyncRequestable):
    async def bulk_dns(self, domains: list[str]) -> list[BulkDNSResult]:
        """Perform bulk DNS lookups asynchronously."""
        csv_response = await self._make_csv_request(build_bulk_dns_params(domains))
        return cast(
            "list[BulkDNSResult]",
            csv_to_dict_list(csv_response) if csv_response else [],
        )

    async def bulk_whois(
        self, items: list[str], lookup_type: BulkWhoisType = BulkWhoisType.LIVE
    ) -> list[BulkWhoisResult]:
        """Perform bulk WHOIS lookups asynchronously."""
        csv_response = await self._make_csv_request(
            build_bulk_whois_params(items, lookup_type)
        )
        return cast(
            "list[BulkWhoisResult]",
            csv_to_dict_list(csv_response) if csv_response else [],
        )

    async def bulk_whois_ip(self, domains: list[str]) -> list[BulkWhoisResult]:
        """Perform bulk domain IP WHOIS lookups asynchronously."""
        csv_response = await self._make_csv_request(build_bulk_whois_ip_params(domains))
        return cast(
            "list[BulkWhoisResult]",
            csv_to_dict_list(csv_response) if csv_response else [],
        )


# --- END GENERATED ---
