"""DNS endpoint mixins (sync and async).

_DNSMixin and _AsyncDNSMixin are intentionally near-identical.
Python requires 'await' inside 'async def'; the two classes cannot share
implementation while maintaining correct coroutine semantics, mypy strict
compliance, and IDE support. All extractable logic lives in parameter-builder
modules and deserializers.py; what remains is structural boilerplate.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from ._base_client import _AsyncRequestable, _SyncRequestable
from ._params.dns import build_dns_params
from .deserializers import parse_dns_result

if TYPE_CHECKING:
    from .models import DNSRecordType, DNSResult


class _DNSMixin(_SyncRequestable):
    def dns_lookup(
        self,
        query: str,
        record_types: list[str | DNSRecordType] | None = None,
    ) -> DNSResult:
        """Perform DNS lookup for a domain or hostname."""
        params = build_dns_params(query, record_types)
        return parse_dns_result(self._make_json_request(params))


# --- BEGIN GENERATED ---
# Async counterpart of the sync class above — generated by scripts/generate_mixins.py
# Edit the sync class, then run `make gen-mixins` to regenerate.
class _AsyncDNSMixin(_AsyncRequestable):
    async def dns_lookup(
        self,
        query: str,
        record_types: list[str | DNSRecordType] | None = None,
    ) -> DNSResult:
        """Perform DNS lookup for a domain or hostname asynchronously."""
        params = build_dns_params(query, record_types)
        return parse_dns_result(await self._make_json_request(params))


# --- END GENERATED ---
