"""Limits endpoint mixins (sync and async).

_LimitsMixin and _AsyncLimitsMixin are intentionally near-identical; the async
counterpart is generated from the sync class by scripts/generate_mixins.py.
Edit the sync class, then run `make gen-mixins` to regenerate.
"""

from __future__ import annotations

from typing import Any

from ._base_client import _AsyncRequestable, _SyncRequestable
from ._params.limits import build_limits_params
from .utils import validate_api_dict


class _LimitsMixin(_SyncRequestable):
    def account_limits(self) -> dict[str, Any]:
        """Get the account's API usage limits and remaining credits."""
        return validate_api_dict(
            self._make_json_request(build_limits_params()), "LimitsResult"
        )


# --- BEGIN GENERATED ---
# Async counterpart of the sync class above — generated by scripts/generate_mixins.py
# Edit the sync class, then run `make gen-mixins` to regenerate.
class _AsyncLimitsMixin(_AsyncRequestable):
    async def account_limits(self) -> dict[str, Any]:
        """Get the account's API usage limits and remaining credits asynchronously."""
        return validate_api_dict(
            await self._make_json_request(build_limits_params()), "LimitsResult"
        )


# --- END GENERATED ---
