"""Queue endpoint mixins (sync and async).

_QueueMixin and _AsyncQueueMixin are intentionally near-identical; the async
counterpart is generated from the sync class by scripts/generate_mixins.py.
Edit the sync class, then run `make gen-mixins` to regenerate.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from ._base_client import _AsyncRequestable, _SyncRequestable
from ._params.queue import build_queue_params, build_submit_queued_params
from .deserializers import parse_queue_result

if TYPE_CHECKING:
    from ._models import QueueResult


class _QueueMixin(_SyncRequestable):
    def check_queue(self, request_hash: str, action: str) -> QueueResult:
        """Poll the status or result of a queued API request."""
        return parse_queue_result(
            self._make_json_request(build_queue_params(request_hash, action))
        )

    def submit_queued(self, service: str, **params: str | int | bool) -> QueueResult:
        """Submit a queued request; poll it with check_queue."""
        return parse_queue_result(
            self._make_json_request(build_submit_queued_params(service, params))
        )


# --- BEGIN GENERATED ---
# Async counterpart of the sync class above — generated by scripts/generate_mixins.py
# Edit the sync class, then run `make gen-mixins` to regenerate.
class _AsyncQueueMixin(_AsyncRequestable):
    async def check_queue(self, request_hash: str, action: str) -> QueueResult:
        """Poll the status or result of a queued API request asynchronously."""
        return parse_queue_result(
            await self._make_json_request(build_queue_params(request_hash, action))
        )

    async def submit_queued(
        self, service: str, **params: str | int | bool
    ) -> QueueResult:
        """Submit a queued request; poll it with check_queue asynchronously."""
        return parse_queue_result(
            await self._make_json_request(build_submit_queued_params(service, params))
        )


# --- END GENERATED ---
