"""Report endpoint mixins (sync and async).

_ReportMixin and _AsyncReportMixin are intentionally near-identical.
Python requires 'await' inside 'async def'; the two classes cannot share
implementation while maintaining correct coroutine semantics, mypy strict
compliance, and IDE support. All extractable logic lives in parameter-builder
modules and deserializers.py; what remains is structural boilerplate.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, cast

from ._base_client import _AsyncRequestable, _SyncRequestable
from ._params.reports import (
    build_domain_report_params,
    build_email_report_params,
    build_ip_report_params,
    build_name_report_params,
    build_organization_report_params,
)
from .deserializers import parse_domain_report, parse_ip_report_result

if TYPE_CHECKING:
    from ._models import (
        DomainReport,
        EmailReportResult,
        IpReportResult,
        NameReportResult,
        OrganizationReportResult,
    )


class _ReportMixin(_SyncRequestable):
    def domain_report(self, domain: str) -> DomainReport:
        """Get comprehensive domain report."""
        return parse_domain_report(
            self._make_json_request(build_domain_report_params(domain))
        )

    def name_report(self, name: str) -> NameReportResult:
        """Get registrant name report."""
        return cast(
            "NameReportResult", self._make_json_request(build_name_report_params(name))
        )

    def organization_report(self, organization: str) -> OrganizationReportResult:
        """Get registrant organization report."""
        return cast(
            "OrganizationReportResult",
            self._make_json_request(build_organization_report_params(organization)),
        )

    def email_report(self, email: str) -> EmailReportResult:
        """Get registrant email report."""
        return cast(
            "EmailReportResult",
            self._make_json_request(build_email_report_params(email)),
        )

    def ip_report(self, ip: str) -> IpReportResult:
        """Get IP address summary report."""
        return parse_ip_report_result(
            self._make_json_request(build_ip_report_params(ip))
        )


# --- BEGIN GENERATED ---
# Async counterpart of the sync class above — generated by scripts/generate_mixins.py
# Edit the sync class, then run `make gen-mixins` to regenerate.
class _AsyncReportMixin(_AsyncRequestable):
    async def domain_report(self, domain: str) -> DomainReport:
        """Get comprehensive domain report asynchronously."""
        return parse_domain_report(
            await self._make_json_request(build_domain_report_params(domain))
        )

    async def name_report(self, name: str) -> NameReportResult:
        """Get registrant name report asynchronously."""
        return cast(
            "NameReportResult",
            await self._make_json_request(build_name_report_params(name)),
        )

    async def organization_report(self, organization: str) -> OrganizationReportResult:
        """Get registrant organization report asynchronously."""
        return cast(
            "OrganizationReportResult",
            await self._make_json_request(
                build_organization_report_params(organization)
            ),
        )

    async def email_report(self, email: str) -> EmailReportResult:
        """Get registrant email report asynchronously."""
        return cast(
            "EmailReportResult",
            await self._make_json_request(build_email_report_params(email)),
        )

    async def ip_report(self, ip: str) -> IpReportResult:
        """Get IP address summary report asynchronously."""
        return parse_ip_report_result(
            await self._make_json_request(build_ip_report_params(ip))
        )


# --- END GENERATED ---
