"""Search endpoint mixins (sync and async).

_SearchMixin and _AsyncSearchMixin are intentionally near-identical.
Python requires 'await' inside 'async def'; the two classes cannot share
implementation while maintaining correct coroutine semantics, mypy strict
compliance, and IDE support. All extractable logic lives in parameter-builder
modules and deserializers.py; what remains is structural boilerplate.
"""

from __future__ import annotations

from typing import Unpack

from ._base_client import _AsyncRequestable, _SyncRequestable
from ._models import (
    DomainSearchFilters,
    KeywordMatchType,
    ReverseIpSearchType,
    ReverseMatchType,
    ReverseMxSearchType,
    ReverseSearchResult,
    ReverseSearchType,
    SearchResult,
)
from ._params.search import (
    build_domain_search_params,
    build_reverse_dns_params,
    build_reverse_ip_params,
    build_reverse_mx_params,
    build_reverse_search_params,
)
from .deserializers import parse_reverse_search_result, parse_search_result


class _SearchMixin(_SyncRequestable):
    def domain_search(
        self,
        keywords: list[str],
        conditions: list[str] | None = None,
        match: KeywordMatchType = KeywordMatchType.ANY,
        filters: DomainSearchFilters | None = None,
        **kwargs: Unpack[DomainSearchFilters],
    ) -> SearchResult:
        """Search for domains matching keywords."""
        merged: DomainSearchFilters = {**(filters or {}), **kwargs}
        params = build_domain_search_params(keywords, conditions, match, merged or None)
        return parse_search_result(self._make_json_request(params))

    def reverse_search(
        self,
        search_type: str | ReverseSearchType,
        search_term: str,
        match: ReverseMatchType = ReverseMatchType.CONTAINS,
    ) -> ReverseSearchResult:
        """Perform reverse search by email, name, or organization."""
        return parse_reverse_search_result(
            self._make_json_request(
                build_reverse_search_params(search_type, search_term, match)
            )
        )

    def reverse_dns(self, domain: str) -> ReverseSearchResult:
        """Perform reverse DNS search."""
        return parse_reverse_search_result(
            self._make_json_request(build_reverse_dns_params(domain))
        )

    def reverse_ip(
        self, search_type: ReverseIpSearchType | str, data: str
    ) -> ReverseSearchResult:
        """Perform reverse IP search."""
        return parse_reverse_search_result(
            self._make_json_request(build_reverse_ip_params(search_type, data))
        )

    def reverse_mx(
        self, search_type: ReverseMxSearchType | str, data: str, recursive: bool = False
    ) -> ReverseSearchResult:
        """Perform reverse MX search."""
        return parse_reverse_search_result(
            self._make_json_request(
                build_reverse_mx_params(search_type, data, recursive)
            )
        )


# --- BEGIN GENERATED ---
# Async counterpart of the sync class above — generated by scripts/generate_mixins.py
# Edit the sync class, then run `make gen-mixins` to regenerate.
class _AsyncSearchMixin(_AsyncRequestable):
    async def domain_search(
        self,
        keywords: list[str],
        conditions: list[str] | None = None,
        match: KeywordMatchType = KeywordMatchType.ANY,
        filters: DomainSearchFilters | None = None,
        **kwargs: Unpack[DomainSearchFilters],
    ) -> SearchResult:
        """Search for domains matching keywords asynchronously."""
        merged: DomainSearchFilters = {**(filters or {}), **kwargs}
        params = build_domain_search_params(keywords, conditions, match, merged or None)
        return parse_search_result(await self._make_json_request(params))

    async def reverse_search(
        self,
        search_type: str | ReverseSearchType,
        search_term: str,
        match: ReverseMatchType = ReverseMatchType.CONTAINS,
    ) -> ReverseSearchResult:
        """Perform reverse search by email, name, or organization asynchronously."""
        return parse_reverse_search_result(
            await self._make_json_request(
                build_reverse_search_params(search_type, search_term, match)
            )
        )

    async def reverse_dns(self, domain: str) -> ReverseSearchResult:
        """Perform reverse DNS search asynchronously."""
        return parse_reverse_search_result(
            await self._make_json_request(build_reverse_dns_params(domain))
        )

    async def reverse_ip(
        self, search_type: ReverseIpSearchType | str, data: str
    ) -> ReverseSearchResult:
        """Perform reverse IP search asynchronously."""
        return parse_reverse_search_result(
            await self._make_json_request(build_reverse_ip_params(search_type, data))
        )

    async def reverse_mx(
        self, search_type: ReverseMxSearchType | str, data: str, recursive: bool = False
    ) -> ReverseSearchResult:
        """Perform reverse MX search asynchronously."""
        return parse_reverse_search_result(
            await self._make_json_request(
                build_reverse_mx_params(search_type, data, recursive)
            )
        )


# --- END GENERATED ---
