"""Backward-compatible model exports.

The concrete model definitions live in ``domainiq._models`` so the package can
keep enums, dataclass responses, filters, and TypedDict responses separated
without breaking existing ``domainiq.models`` imports.
"""

from ._models import (
    BulkDNSResult,
    BulkWhoisResult,
    BulkWhoisType,
    DNSRecord,
    DNSRecordType,
    DNSResult,
    DomainCategory,
    DomainReport,
    DomainSearchFilters,
    DomainSnapshot,
    EmailReportResult,
    IpReportResult,
    KeywordMatchType,
    MatchType,
    MonitorActionResult,
    MonitorItem,
    MonitorItemOptions,
    MonitorItemType,
    MonitorReport,
    MonitorReportType,
    NameReportResult,
    OrganizationReportResult,
    QueueResult,
    ReverseIpSearchType,
    ReverseMatchType,
    ReverseMxSearchType,
    ReverseSearchResult,
    ReverseSearchType,
    SearchResult,
    SnapshotOptions,
    WhoisResult,
)

__all__ = [
    "BulkDNSResult",
    "BulkWhoisResult",
    "BulkWhoisType",
    "DNSRecord",
    "DNSRecordType",
    "DNSResult",
    "DomainCategory",
    "DomainReport",
    "DomainSearchFilters",
    "DomainSnapshot",
    "EmailReportResult",
    "IpReportResult",
    "KeywordMatchType",
    "MatchType",
    "MonitorActionResult",
    "MonitorItem",
    "MonitorItemOptions",
    "MonitorItemType",
    "MonitorReport",
    "MonitorReportType",
    "NameReportResult",
    "OrganizationReportResult",
    "QueueResult",
    "ReverseIpSearchType",
    "ReverseMatchType",
    "ReverseMxSearchType",
    "ReverseSearchResult",
    "ReverseSearchType",
    "SearchResult",
    "SnapshotOptions",
    "WhoisResult",
]
