"""Internal model modules used by the public compatibility wrapper."""

from .enums import (
    BulkWhoisType,
    DNSRecordType,
    KeywordMatchType,
    MatchType,
    MonitorItemType,
    MonitorReportType,
    ReverseIpSearchType,
    ReverseMatchType,
    ReverseMxSearchType,
    ReverseSearchType,
)
from .filters import DomainSearchFilters
from .results import (
    DNSRecord,
    DNSResult,
    DomainCategory,
    DomainReport,
    DomainSnapshot,
    MonitorItem,
    MonitorReport,
    SnapshotOptions,
    WhoisResult,
)
from .typed import (
    BulkDNSResult,
    BulkWhoisResult,
    EmailReportResult,
    IpReportResult,
    MonitorActionResult,
    NameReportResult,
    OrganizationReportResult,
    ReverseSearchResult,
    SearchResult,
)

__all__ = [
    "BulkDNSResult",
    "BulkWhoisResult",
    "BulkWhoisType",
    "DNSRecord",
    "DNSRecordType",
    "DNSResult",
    "DomainCategory",
    "DomainReport",
    "DomainSearchFilters",
    "DomainSnapshot",
    "EmailReportResult",
    "IpReportResult",
    "KeywordMatchType",
    "MatchType",
    "MonitorActionResult",
    "MonitorItem",
    "MonitorItemType",
    "MonitorReport",
    "MonitorReportType",
    "NameReportResult",
    "OrganizationReportResult",
    "ReverseIpSearchType",
    "ReverseMatchType",
    "ReverseMxSearchType",
    "ReverseSearchResult",
    "ReverseSearchType",
    "SearchResult",
    "SnapshotOptions",
    "WhoisResult",
]
